### ISSUE TITLE
typo rdfs:label "for mapping" in owlstar.ttl

### ISSUE THREAD

**Issue by wdduncan** [cmungall/owlstar#4]
Need to correct `rdfs:label "for mapping" ` in owlstar.ttl

```
os:folMapping a owl:AnnotationProperty ;
  rdfs:label "for mapping" ;
  dc:description "An owlstar mapping from an RDF* structure to an FOL axiom. TBD: Prover9 syntax vs CL" .
```

**Comment by sierra-moxon** [comment]
Going to close for now, I think we can reopen if need be, but linkml-owlstar isn't currently active.  If you have an idea of what you want to change the label to, @wdduncan, let me know? :)
