### ISSUE TITLE
spatial os:context?

### ISSUE THREAD

**Issue by wdduncan** [cmungall/owlstar#5]
Currently `os:context` is only for time, but you might want to consider spatial context too.
I'm thinking here about levels of granularity. At one level of granularity a nucleus is part of a cell. At a lower level of granularity a nucleus is located in an anatomical space within the cell.

**Comment by cmungall** [comment]
You could certainly do this. I don't think it's necessarily a good idea to make class-level assertions that are spatial context dependent, especially so for whether a nucleus is a part of a cell (it is, by the GO definition).

Can you provide an instance level example?

**Comment by wdduncan** [comment]
No, no particular instance examples come to mind.  
There more high-level considerations that might come to mind with regard to representing rates (e.g., acceleration) that might make use of spatial context. But, I'd have to think about it.

**Comment by sierra-moxon** [comment]
Going to close for now, I think we can reopen if need be, but linkml-owlstar isn't currently active.  :)
