### ISSUE TITLE
semantic os:context?

### ISSUE THREAD

**Issue by wdduncan** [cmungall/owlstar#6]
Not sure that the subject line for this should be, but for now I'll call it "semantic context". 
My motivation is comes from all the EMR translation work I've done. Consider a fake dental record that looks like this:

patient_id: 1001
tooth_number: 1 
surface: MO
procedure_code: 2391
procedure_date: 2010-01-01

Basically this record is about a composite filling restoration procedure that restored the mesial and occlusal surfaces on patient 1001's lower right wisdom tooth.

Translating such records into OWL can be quite labor intensive.  My thought is use the context to express what the values in the record represent. E.g.:
```
<< _:b1 :patient_id "1001" >> os:semanticContext :Patient  .                   # this triple is represents a patient
<< _:b1 :tooth_number "1" >> os:semanticsContext :WisdomTooth .     # this triple is represents a wisdom tooth
<< _:b1 :surface "MO" >> os:semanticContext :MesialSurface, :OclussalSurface . # this triple represents the mesial and occlusal surfaces on a tooth
<< _:b1 :procedure_code "2391">> os:semanticContext :CompositeRestoration . # this triple represents a composite restoration procedure
```
Now we could execute a query search for all patient ids that had a composite restoration performed on the mesial surface on a molar (wisdom teeth are kinds of molars).

If we wish to include in the semantic context that the tooth is part of the patient, perhaps something like this would work:
```
<< _:b1 :tooth_number "1" >> os:semanticsContext :WisdomTooth, [:partOf _b1] .
```
Also, it might be worthwhile to separately identify the contexts of the subject, predicate, and object:
```
<< _:b1 :tooth_number "1" >> 
                     os:subjectContext :Patient;
                     os:objectContext :WisdomTooth .
```

**Comment by cmungall** [comment]
I'm not sure I understand the motivation. It may or may not be possible I'd have to understand more. But it feels like this is not what contexts are intended for.

I don't understand the motivation for subject/object contexts.

See `that` in http://www.ihmc.us/users/phayes/IKL/GUIDE/GUIDE.html for examples

I suggest thinking of the os:context triple as nothing more than a quotation mechanism. i.e. a way of talking about a statement/assertion/state-of-affairs/axiom without actually asserting it to be true.

**Comment by wdduncan** [comment]
My motivation I am thinking about medical records that have information about patients.
This would be a means to quickly represent that the system has information about the patient that may/may not be true. Similar approach could be taken for documents and questionnaires.

This fits well within the framework of quotation. Perhaps you mean something else by `os:context`.
The IKL stuff is interesting but may take us too far off track.

**Comment by sierra-moxon** [comment]
Going to close for now, I think we can reopen if need be, but linkml-owlstar isn't currently active.
